all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=orangehrm_3.0.1'
      username: orangehrm-3.0.1
      password: orangehrm-3.0.1
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=test_orangehrm_3.0.1'
      username: orangehrm-3.0.1
      password: orangehrm-3.0.1